[package]
name = "miner"
version = "0.1.0"
edition = "2024"
default-run = "miner"

[dependencies]
anyhow = "1.0.99"
btclib = { path = "../lib" }
clap = { version = "4.5.47", features = ["derive"] }
flume = "0.11.1"
tokio = { version = "1.47.1", features = ["full"] }
